### ISSUE TITLE
AssertionError: can't download image

### ISSUE THREAD

**Issue by shrx** [michaelnmmeyer/scribd_dl#1]
```
./bin/scribd_dl.py http://www.scribd.com/doc/56788222/Liquid-Crystal-Walk-Through
https://html1-f.scribdassets.com/86cvzsz668ziduf/images/6-74a60ade9c.jpg
Traceback (most recent call last):
  File "./bin/scribd_dl.py", line 86, in <module>
    files = download_pages(links, out_dir)
  File "./bin/scribd_dl.py", line 56, in download_pages
    image = download_image(link)
  File "./bin/scribd_dl.py", line 48, in download_image
    assert r.status_code == 200, "can't download image at '%s'" % url
AssertionError: can't download image at 'https://html1-f.scribdassets.com/86cvzsz668ziduf/images/6-74a60ade9c.jpg'
```

System info:
OS X 10.10.3
Python 3.4.3
requests 2.7.0
imagemagick 6.9.1-6

**Comment by michaelnmmeyer** [comment]
I looked at the issue.

There is no practical way of generating a PDF from this type of document, because, in this case, the documents text is inlined into the html page instead of being part of an image. There is a program `html2ps` that could help, but it doesn't understand UTF-8 nor supports correctly CSS properties, wich makes it output total garbage.

At best, it might be possible to generate a static html page with a set of images.

**Comment by michaelnmmeyer** [comment]
Won't support this. See #b88475fc8700b87f72a544d4ae3c356d09e80287
